[supervisord]
nodaemon=true

[program:bot]
command=python3 bot.py
autostart=true
autorestart=true
exitcodes=0
stderr_logfile=/var/log/bot.err.log
stdout_logfile=/var/log/bot.out.log

[program:webhook]
command=python3 webhook.py
autostart=true
autorestart=true
exitcodes=0
stderr_logfile=/var/log/webhook.err.log
stdout_logfile=/var/log/webhook.out.log

[program:update]
command=bash update.sh
autostart=true
autorestart=true
exitcodes=0
stderr_logfile=/var/log/update.err.log
stdout_logfile=/var/log/update.out.log

[program:auto_fix]
command=python3 auto_fix.py
autostart=true
autorestart=true
exitcodes=0
stderr_logfile=/var/log/auto_fix.err.log
stdout_logfile=/var/log/auto_fix.out.log

[program:handler_loader]
command=python3 handler_loader.py
autostart=true
autorestart=true
exitcodes=0
stderr_logfile=/var/log/handler_loader.err.log
stdout_logfile=/var/log/handler_loader.out.log