[supervisord]
nodaemon=true

[program:bot]
command=python3 bot.py
autostart=true
autorestart=true
exitcodes=0
stderr_logfile=/var/log/bot.err.log
stdout_logfile=/var/log/bot.out.log

[program:webhook]
command=python3 webhook.py
autostart=true
autorestart=true
exitcodes=0
stderr_logfile=/var/log/webhook.err.log
stdout_logfile=/var/log/webhook.out.log