[supervisord]
nodaemon=true

[program:update]
command=/bin/bash /app/update.sh
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout

[program:gunicorn]
command=gunicorn -b 0.0.0.0:9000 webhook:app
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout

[program:bot]
command=python bot.py
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout