name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change to your branch name if needed
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: sexbhabhinew
          password: sexbhabhinew

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: sexbhabhinew/new-bot:latest  # Change to your Docker Hub repo

      - name: Verify Docker Image
        run: docker images | grep my-bot
